#define _GNU_SOURCE 1
#include "container.h"
#include "log.h"
#include "mount.h"
#include "netlink.h"
#include "sec.h"
#include "user.h"
#include <arpa/inet.h>
#include <fcntl.h>
#include <net/if.h>
#include <sched.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mount.h>
#include <sys/socket.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#ifndef VETH_INFO_PEER
#define VETH_INFO_PEER 1
#endif

/* ========== 辅助函数：启用 ICMP datagram socket（允许 user ns 中 ping）
 * ========== */
static int enable_ping_dgram(void) {
  const char *path = "/proc/sys/net/ipv4/ping_group_range";
  int fd = open(path, O_WRONLY);
  if (fd < 0) {
    log_warn("cannot open %s", path);
    return -1;
  }
  /* "0 65535" = 允许所有 GID 使用 ICMP dgram socket */
  ssize_t n = write(fd, "0 65535\n", 8);
  close(fd);
  if (n != 8) {
    log_warn("failed to write ping_group_range");
    return -1;
  }
  log_debug("ping_group_range set to 0 65535");
  return 0;
}

/* ========== 辅助函数：写入 DNS 配置 ========== */
static int setup_dns(const char *dns_server) {
  if (!dns_server) {
    return 0;
  }

  log_debug("configuring DNS: %s", dns_server);

  /* 确保 /etc/resolv.conf 存在 */
  int fd = open("/etc/resolv.conf", O_WRONLY | O_CREAT | O_TRUNC, 0644);
  if (fd < 0) {
    log_warn("cannot open /etc/resolv.conf: %m");
    return -1;
  }

  char buf[256];
  int len = snprintf(buf, sizeof(buf),
                     "# generated by barco\n"
                     "nameserver %s\n"
                     "nameserver 8.8.4.4\n"
                     "options timeout:2 attempts:3\n",
                     dns_server);

  ssize_t n = write(fd, buf, len);
  close(fd);

  if (n != len) {
    log_warn("failed to write /etc/resolv.conf");
    return -1;
  }

  log_debug("DNS configured: primary=%s, secondary=8.8.4.4", dns_server);
  return 0;
}

/* ========== 辅助函数：挂载必要的伪文件系统 ========== */
static int mount_pseudo_fs(void) {
  /* 确保 /proc 存在（在 pivot_root 后可能丢失） */
  if (mount("proc", "/proc", "proc", MS_NODEV | MS_NOEXEC | MS_NOSUID, NULL) <
      0) {
    /* 可能已经挂载，不算致命错误 */
    log_debug("mount /proc: %m (may already be mounted)");
  }

  /* 确保 /sys 存在 */
  if (mount("sysfs", "/sys", "sysfs",
            MS_NODEV | MS_NOEXEC | MS_NOSUID | MS_RDONLY, NULL) < 0) {
    log_debug("mount /sys: %m (may already be mounted)");
  }

  return 0;
}

/**
 * 容器启动函数（由 clone() 调用）
 */
int container_start(void *arg) {
  container_config *config = (container_config *)arg;
  int fd_closed = 0;

  log_debug("starting container in new namespaces");

  /* ========== 阶段 1：基础隔离配置 ========== */

  if (config->hostname &&
      sethostname(config->hostname, strlen(config->hostname)) < 0) {
    log_error("sethostname failed: %m");
    goto fail;
  }

  if (mount_set(config->mnt) < 0) {
    log_error("mount_set failed");
    goto fail;
  }

  /* ========== 阶段 2：网络配置（在 user_namespace_init 之前）========== */

  if (config->veth_name && config->container_ip) {
    log_debug("configuring container network: %s <- %s", config->veth_name,
              config->container_ip);

    /* 启用 lo 接口 */
    if (nl_set_up("lo") < 0) {
      log_warn("failed to bring up lo (non-fatal)");
    }

    /* 等待临时接口 veth_tmp 出现在本命名空间 */
    if (config->veth_tmp) {
      int waited = 0;
      const int timeout_ms = 5000;
      log_debug("waiting for interface %s to appear...", config->veth_tmp);
      while (if_nametoindex(config->veth_tmp) == 0 && waited < timeout_ms) {
        usleep(100000); /* 100ms */
        waited += 100;
      }
      if (waited >= timeout_ms) {
        log_error("timed out waiting for interface %s", config->veth_tmp);
        goto fail;
      }
      log_debug("interface %s is now visible", config->veth_tmp);

      /* 重命名为用户指定的名称 */
      if (nl_rename_link(config->veth_tmp, config->veth_name) < 0) {
        log_error("failed to rename %s to %s", config->veth_tmp,
                  config->veth_name);
        goto fail;
      }
      log_debug("renamed to %s", config->veth_name);
    }

    /* 添加 IP 地址并启用 */
    if (nl_add_addr(config->veth_name, config->container_ip) < 0) {
      log_error("failed to add IP %s to %s", config->container_ip,
                config->veth_name);
      goto fail;
    }

    if (nl_set_up(config->veth_name) < 0) {
      log_error("failed to bring up %s", config->veth_name);
      goto fail;
    }

    /* 添加默认路由（网关来自 host_ip） */
    if (config->host_ip) {
      char host_gw[INET_ADDRSTRLEN];
      const char *slash = strchr(config->host_ip, '/');
      size_t addr_len =
          slash ? (size_t)(slash - config->host_ip) : strlen(config->host_ip);

      if (addr_len >= sizeof(host_gw)) {
        log_error("host IP address too long");
        goto fail;
      }
      memcpy(host_gw, config->host_ip, addr_len);
      host_gw[addr_len] = '\0';

      if (nl_add_route("default", host_gw, config->veth_name) < 0) {
        log_warn("failed to add default route via %s (non-fatal)", host_gw);
      } else {
        log_debug("default route added via %s", host_gw);
      }
    }

    log_info("network configured: %s (%s) <-> host", config->veth_name,
             config->container_ip);
  }

  /* 配置 DNS（在失去特权之前写入） */
  if (config->dns_server) {
    setup_dns(config->dns_server);
  }

  /* 启用 ping datagram socket（在失去特权之前） */
  enable_ping_dgram();

  /* 初始化用户命名空间（之后将失去特权） */
  if (user_namespace_init(config->uid, config->fd) < 0) {
    log_error("user_namespace_init failed");
    goto fail;
  }

  /* ========== 阶段 3：安全限制 ========== */

  if (sec_set_caps() < 0) {
    log_error("sec_set_caps failed");
    goto fail;
  }

  if (sec_set_seccomp() < 0) {
    log_error("sec_set_seccomp failed");
    goto fail;
  }

  /* ========== 阶段 4：清理并执行用户命令 ========== */

  log_debug("closing container socket...");
  if (close(config->fd) < 0) {
    log_error("failed to close container socket: %m");
    goto fail;
  }
  fd_closed = 1;

  log_debug("executing: %s %s (cwd: %s)", config->cmd,
            config->arg ? config->arg : "", config->mnt);
  log_info("### BARCONTAINER STARTED - type 'exit' to quit ###");

  char *argv[3] = {config->cmd, config->arg, NULL};

  if (execve(config->cmd, argv, NULL) < 0) {
    log_error("execve '%s' failed: %m", config->cmd);
    goto fail;
  }

  return 0;

fail:
  if (!fd_closed && config->fd >= 0) {
    close(config->fd);
  }
  return -1;
}

/**
 * 创建容器进程（使用 clone 实现命名空间隔离）
 */
int container_init(container_config *config, char *stack) {
  int flags = CLONE_NEWNS | CLONE_NEWCGROUP | CLONE_NEWPID | CLONE_NEWIPC |
              CLONE_NEWNET | CLONE_NEWUTS | SIGCHLD;

  log_debug("cloning container process with flags: 0x%x", flags);

  int pid = clone(container_start, stack, flags, config);
  if (pid < 0) {
    log_error("clone failed: %m");
    return -1;
  }

  log_debug("container process created: pid=%d", pid);

  /* 父进程关闭传递给子进程的 socket 副本 */
  if (config->fd >= 0) {
    close(config->fd);
    config->fd = -1;
  }

  return pid;
}

/**
 * 等待容器进程退出并获取退出状态
 */
int container_wait(int container_pid) {
  int status = 0;

  log_debug("waiting for container pid=%d", container_pid);

  if (waitpid(container_pid, &status, 0) < 0) {
    log_error("waitpid failed: %m");
    return -1;
  }

  if (WIFEXITED(status)) {
    int exit_code = WEXITSTATUS(status);
    log_debug("container exited with code: %d", exit_code);
    return exit_code;
  } else if (WIFSIGNALED(status)) {
    log_warn("container killed by signal: %d", WTERMSIG(status));
    return 128 + WTERMSIG(status);
  }

  return -1;
}

/**
 * 强制终止容器进程
 */
void container_stop(int container_pid) {
  log_debug("sending SIGKILL to container pid=%d", container_pid);

  if (kill(container_pid, SIGKILL) < 0) {
    log_error("kill failed: %m");
    return;
  }

  waitpid(container_pid, NULL, 0);
  log_debug("container pid=%d terminated", container_pid);
}
